/control/verbose  0
/run/verbose      0		
/event/verbose    0
/tracking/verbose 0

/run/random/setRandomSeed 12346

/gps/pos/type    Volume
/gps/pos/shape   Sphere
/gps/pos/centre  0. 0. 0. cm
/gps/pos/radius  1 cm
/gps/pos/confine SourceCore
/gps/ang/type   iso

/grdm/BRbias 0
/grdm/fBeta 0
/grdm/verbose 0
/grdm/analogueMC 1


#
#/gps/position 0 0 0
/gps/particle ion
/gps/energy 0. eV
# 60Co
#/gps/ion 27 60
# 44Ti
#/gps/ion 22 44
# 137Cs
#/gps/ion 55 137
# 54Mn
/gps/ion 25 54
